name: bera_plugin
description: "A new Flutter package project."
version: 0.0.1
homepage: "null"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.5
  dio: ^5.4.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_database: ^10.4.6
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  geolocator: ^11.0.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
